project:
  type: book
  output-dir: _site
  render:
    - "*.qmd"
  resources:
    - assets/**
    - versions.json

bibliography: references.bib

book:
  title: "Easy Electrophysiology"
  favicon: assets/favicon.jpg
  search: true
  page-navigation: true
  site-url: https://easy-electrophysiology.github.io/manual/
  sidebar:
    title: "Easy Electrophysiology<br>Manual"
    logo: assets/logo.jpg
    style: docked
    collapse-level: 1
  page-footer:
    left: "Easy Electrophysiology User Manual"
    right: "Built with [Quarto](https://quarto.org)."
  chapters:
    - index.qmd
    - part: "Get started"
      chapters:
        - loading-files.qmd
        - graphical-interface-overview.qmd
        - analysis-overview.qmd
    - part: "Analysis"
      chapters:
        - curve-fitting.qmd
        - href: event-detection-and-analysis.qmd
          text: "Events detection and kinetics"
        - events-analysis.qmd
        - href: action-potential-counting.qmd
          text: "AP counting"
        - href: action-potential-kinetics.qmd
          text: "AP kinetics"
        - input-resistance.qmd
        - burst-analysis.qmd
        - analysis.qmd
        - analyzing-in-batch-mode.qmd
    - part: "Data tools"
      chapters:
        - upsample.qmd
        - downsample.qmd
        - filter.qmd
        - detrend.qmd
        - remove-baseline.qmd
        - average-records.qmd
        - record-arithmetic.qmd
        - stimulus-artefact-removal.qmd
        - reshape-records.qmd
        - normalize-time.qmd
        - cut-trace-length.qmd
        - reset-to-raw-data.qmd
    - part: "Saving and export"
      chapters:
        - saving-data-and-analysis-results.qmd
        - plot-exporter.qmd
    - saving-and-resetting-default-options.qmd
    - graph-options.qmd
    - legacy-options.qmd
    - keyboard-shortcuts.qmd
    - acknowledgements.qmd
    - references.qmd
  appendices:
    - mathematical-formulas.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    include-after-body: assets/version-selector.html
    toc: true
    number-sections: false
    fig-align: center
    link-external-newwindow: true
