---
title: "Analysis overview"
---

The [Analysis]{.ui-label} window is used to switch between analysis types and can be accessed through [File]{.ui-label} › [Open Analysis Window]{.ui-label}.

The available analyses are determined by the recording type. *Curve Fitting* and *Event Detection* are supported for both voltage-clamp and current-clamp recordings. *Action Potential Counting*, *Action Potential Kinetics*, and *Input Resistance* are available only for current-clamp recordings.

For maximum flexibility, each analysis type is independent and can be run concurrently. This means it is possible to switch from one analysis type to another mid-analysis without overwriting results. The relevant plots and results tables will be updated on analysis change.

![Switching analysis. The analysis type can be switched in the [Analysis]{.ui-label} window, opened from [File]{.ui-label} › [Open Analysis Window]{.ui-label}. Switching analysis displays the relevant options in the panel on the left.](images/media/image6.png)
