---
title: "GUI overview"
---

The [Plot]{.ui-label} and [Table]{.ui-label} views are the two main ways to visualize data and results in Easy Electrophysiology, accessed through the [Plot]{.ui-label} and [Table]{.ui-label} tabs. The [Plot]{.ui-label} tab is used to view voltage (Vm) and current (Im) traces, set up and run analysis, and visualize the results. The [Table]{.ui-label} tab displays results in table format with options for saving to Excel or CSV.

To choose an analysis to run, select [File]{.ui-label} › [Open Analysis Window]{.ui-label}. When an analysis type is selected, the [Analysis Panel]{.ui-label} on the left-hand side of the [Plot]{.ui-label} tab will show the relevant options for running that analysis.

In the [Table]{.ui-label} view, options for saving analysis results can be found using the dropdown in the [Save Table]{.ui-label} box. Results can be saved as `.xlsx` (includes border formatting) or as `.csv` (no formatting). For some analyses (*Events*, *Action Potential Counting, Input Resistance*), checkboxes in the left-hand panel can be used to select which results to display.

![Graphical interface overview. File data and analysis results are displayed in the [Plot]{.ui-label} tab graph, and tabular analysis results are displayed in the [Table]{.ui-label} tab. The [Analysis Panel]{.ui-label} (bottom left) contains options for analysis when an analysis type is selected. The buttons in the [Record]{.ui-label} box (top left) and the scrollbar under the graph can be used to move through records.](images/media/image1.png)

## Zooming and panning the graph

There are two zoom and pan modes available when using the [Plot]{.ui-label} tab graph to explore your data. By default, [One Button]{.ui-label} mode is selected and you can zoom by clicking anywhere on the plot and dragging the mouse to draw a box to zoom in to. To unzoom, right-click the graph and select [Undo Zoom]{.ui-label}.

In the second mode, both mouse buttons can be used to navigate the graph. To access it, right-click anywhere on the graph and select [Mouse Mode]{.ui-label} › [Two button (pan left, zoom right)]{.ui-label}. To zoom, hold down the right mouse button and drag the mouse to dynamically zoom in and out. To pan, click and hold down the left mouse button and drag to move the plot. You can still use [Undo Zoom]{.ui-label} in this mode.
