---
title: "Graph Options"
---

The graphs have a number of customizable display features for clear and convenient data visualization. These can be selected through 'View' \> 'Graph Options'.

*Y Axis Scaling*

-   *All Records* -- the y axis is scaled to that of the record with the largest y-axis range. This ensures the y-axis scale is the same for every record in the file.

-   *Displayed Record* -- the y-axis is rescaled on every record change. This reduces performance when switching between records.

*Plot Size Ratio and Position*

The relative size of the upper and lower plots can be changed using the slider. Clicking the 'Swap Plot Position' button will switch the position of the upper and plot. This is simply aesthetic and will not change the primary data channel.

*Show Gridlines*

This will show / hide the gray gridlines on the upper / lower plot.

*Graph Line Thickness*

This will set the line thickness on the upper and lower plots. It is not recommended to set the plot thickness higher than the default value of 1.0 as this will significantly slow down graphics performance.

*Limit View Range for Performance (Single-record files only).*

For single-record voltage-clamp data the entire dataset can be displayed on the graph at once. However, depending on the length of recording time, this data can be very large and slow performance. '*Limit view range for performance'* will set a maximum window length so only a subset of the data is shown. This is set at 500k samples by default, but the maximum window size can be increased, decreased or this feature turned off.
